### PR TITLE
feat: foundry

### PR DESCRIPTION
**Pull request by sambacha**
foundry configuration

### CODE REVIEW

**Comment by ind-igo** [comment]
Much appreciated ser. Still wondering if we want to keep dapptools/foundry in this repo, but all new repos are being built with Foundry.

**Comment by sambacha** [comment]
> Much appreciated ser. Still wondering if we want to keep dapptools/foundry in this repo, but all new repos are being built with Foundry.

I will update the nix setup then. Foundry is largely compatible with dapptools, I can provide a map-out of the differences

**Comment by ind-igo** [comment]
It's large change to our tools infrastructure. Requires some time and focus.

**Review by philipjonsen — APPROVED** [review]

**Comment by sambacha** [comment]
> It's large change to our tools infrastructure. Requires some time and focus.

done. see https://github.com/OlympusDAO/olympus-contracts/pull/311

closing this PR for [311](https://github.com/OlympusDAO/olympus-contracts/pull/311), cheers

**Pull request closed without merging**
